export default {
  type: "object",
  properties: {
    title: { type: "string" },
    description: { type: "string" },
    author: { type: "string" },
    publishingCompany: { type: "string" },
    publishYear: { type: "integer" },
    isbn: { type: "string" },
    pages: { type: "integer" },
    imageURL: { type: "string" },
    isAvailable: { type: "boolean" },
    createDate: { type: "string", format: "date-time" },
    updatedDate: { type: "string", format: "date-time" },
    deletedDate: { type: "string", format: "date-time" },
    rentMaxDays: { type: "integer" },
  },
  required: [
    "title",
    "description",
    "author",
    "publishingCompany",
    "publishYear",
    "isbn",
    "isAvailable",
    "createDate",
    "rentMaxDays",
  ],
  additionalProperties: false,
};
